name: tests

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/**.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/**.md'
  workflow_dispatch: {}

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:

    - name: setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run e2e tests
      run: make test.e2e
